package de.hdm.thies.matrix;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class AllocationException extends Exception {

    /**
     * AllocationException constructor comment.
     */
    public AllocationException() {
        super();
    }

    /**
     * AllocationException constructor comment.
     * @param s java.lang.String
     */
    public AllocationException(String s) {
        super(s);
    }
}
